---
{% raw -%}
---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  collections:
    - community.aws
  vars:
    instance_configs: "{{ (lookup('file', molecule_instance_config, errors='ignore') or '{}') | from_yaml }}"
  tasks:
    - name: Destroy ephemeral EC2 instance(s)
      ec2_instance:
        instance_ids: "{{ instance_configs | map(attribute='instance_ids') | flatten }}"
        state: absent

    - name: Write Molecule instance configs
      copy:
        dest: "{{ molecule_instance_config }}"
        content: |
          ---
          []
{%- endraw %}
