---
{% raw -%}
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for cloud init to finish
      cloud_init_data_facts:
        filter: status
      register: res
      until: "res.cloud_init_data_facts.status.v1.stage is defined and not res.cloud_init_data_facts.status.v1.stage"
      retries: 100
      delay: 10

    - name: Make sure python3 is installed
      package:
        name: python3
        state: present
      become: true
{%- endraw %}
